import type { ColorThemeDefinition } from "./colorTheme";

/** Sin tema de color: los colores propios de Intermotors (index.css). */
export const DEFAULT_COLOR_THEME_ID = "default";

/**
 * Temas incluidos. Usan las claves de los temas de VS Code de los que salen,
 * así el mismo motor sirve para estos y para los que el usuario importe.
 * Solo hacen falta las claves que la app consume (ver CSS_VARIABLE_SOURCES).
 */
export const PRESET_COLOR_THEMES: ColorThemeDefinition[] = [
  {
    id: "github-light",
    label: "GitHub Claro",
    kind: "light",
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#1f2328",
      descriptionForeground: "#59636e",
      "editorWidget.background": "#f6f8fa",
      "menu.background": "#ffffff",
      "button.background": "#1f883d",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#ebecf0",
      "textLink.foreground": "#0969da",
      focusBorder: "#0969da",
      "input.background": "#ffffff",
      "input.border": "#d1d9e0",
      "widget.border": "#d1d9e0",
      "list.hoverBackground": "#eff2f5",
      errorForeground: "#d1242f",
    },
  },
  {
    id: "github-dark",
    label: "GitHub Oscuro",
    kind: "dark",
    colors: {
      "editor.background": "#0d1117",
      "editor.foreground": "#e6edf3",
      descriptionForeground: "#8d96a0",
      "editorWidget.background": "#161b22",
      "menu.background": "#161b22",
      "button.background": "#238636",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#21262d",
      "textLink.foreground": "#4493f8",
      focusBorder: "#1f6feb",
      "input.background": "#0d1117",
      "input.border": "#30363d",
      "widget.border": "#30363d",
      "list.hoverBackground": "#6e76811a",
      errorForeground: "#f85149",
    },
  },
  {
    id: "one-dark",
    label: "One Dark",
    kind: "dark",
    colors: {
      "editor.background": "#282c34",
      "editor.foreground": "#abb2bf",
      descriptionForeground: "#8b929e",
      "editorWidget.background": "#21252b",
      "menu.background": "#21252b",
      "button.background": "#404754",
      "button.secondaryBackground": "#30333d",
      "textLink.foreground": "#61afef",
      focusBorder: "#4d78cc",
      "input.background": "#1d1f23",
      "input.border": "#3e4452",
      "widget.border": "#3e4452",
      "list.hoverBackground": "#2c313a",
      errorForeground: "#e06c75",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    kind: "dark",
    colors: {
      "editor.background": "#282a36",
      "editor.foreground": "#f8f8f2",
      descriptionForeground: "#a6accd",
      "editorWidget.background": "#21222c",
      "menu.background": "#343746",
      "button.background": "#44475a",
      "button.foreground": "#f8f8f2",
      "activityBarBadge.background": "#ff79c6",
      focusBorder: "#6272a4",
      "input.background": "#21222c",
      "input.border": "#191a21",
      "widget.border": "#44475a",
      "list.hoverBackground": "#44475a75",
      errorForeground: "#ff5555",
    },
  },
  {
    id: "nord",
    label: "Nord",
    kind: "dark",
    colors: {
      "editor.background": "#2e3440",
      "editor.foreground": "#d8dee9",
      descriptionForeground: "#a3acbd",
      "editorWidget.background": "#3b4252",
      "menu.background": "#3b4252",
      "button.background": "#5e81ac",
      "button.foreground": "#eceff4",
      "button.secondaryBackground": "#434c5e",
      "textLink.foreground": "#88c0d0",
      focusBorder: "#88c0d0",
      "input.background": "#3b4252",
      "input.border": "#4c566a",
      "widget.border": "#4c566a",
      "list.hoverBackground": "#3b4252",
      errorForeground: "#bf616a",
    },
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    kind: "dark",
    colors: {
      "editor.background": "#1a1b26",
      "editor.foreground": "#c0caf5",
      descriptionForeground: "#9aa5ce",
      "editorWidget.background": "#16161e",
      "menu.background": "#16161e",
      "button.background": "#3d59a1",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#24283b",
      "textLink.foreground": "#7aa2f7",
      focusBorder: "#7aa2f7",
      "input.background": "#16161e",
      "input.border": "#292e42",
      "widget.border": "#292e42",
      "list.hoverBackground": "#1f2335",
      errorForeground: "#f7768e",
    },
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    kind: "light",
    colors: {
      "editor.background": "#eff1f5",
      "editor.foreground": "#4c4f69",
      descriptionForeground: "#6c6f85",
      "editorWidget.background": "#e6e9ef",
      "menu.background": "#eff1f5",
      "button.background": "#8839ef",
      "button.foreground": "#eff1f5",
      "button.secondaryBackground": "#ccd0da",
      "textLink.foreground": "#1e66f5",
      focusBorder: "#8839ef",
      "input.background": "#e6e9ef",
      "input.border": "#bcc0cc",
      "widget.border": "#ccd0da",
      "list.hoverBackground": "#dce0e8",
      errorForeground: "#d20f39",
    },
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    kind: "dark",
    colors: {
      "editor.background": "#1e1e2e",
      "editor.foreground": "#cdd6f4",
      descriptionForeground: "#a6adc8",
      "editorWidget.background": "#181825",
      "menu.background": "#181825",
      "button.background": "#cba6f7",
      "button.foreground": "#11111b",
      "button.secondaryBackground": "#45475a",
      "textLink.foreground": "#89b4fa",
      focusBorder: "#cba6f7",
      "input.background": "#313244",
      "input.border": "#45475a",
      "widget.border": "#313244",
      "list.hoverBackground": "#313244",
      errorForeground: "#f38ba8",
    },
  },
  {
    id: "solarized-light",
    label: "Solarized Claro",
    kind: "light",
    colors: {
      "editor.background": "#fdf6e3",
      "editor.foreground": "#586e75",
      descriptionForeground: "#657b83",
      "editorWidget.background": "#eee8d5",
      "menu.background": "#eee8d5",
      "button.background": "#ac9d57",
      "button.foreground": "#ffffff",
      "button.secondaryBackground": "#e6dfc9",
      "textLink.foreground": "#268bd2",
      focusBorder: "#b58900",
      "input.background": "#eee8d5",
      "input.border": "#d3cbb7",
      "widget.border": "#d3cbb7",
      "list.hoverBackground": "#e8e1cc",
      errorForeground: "#dc322f",
    },
  },
];
